# Generated by Django 3.1.3 on 2020-11-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email_id',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
