# Generated by Django 3.1.3 on 2020-12-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_navigation', '0002_auto_20201127_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=50)),
            ],
        ),
    ]
